name: Run Robot Framework Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          # Tambahkan library lain jika kamu gunakan (misal: RequestsLibrary, Browser, dsb)

      - name: Run Robot Framework tests
        run: |
          sh run_test.sh 

      - name: Upload Robot Framework test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results